### ISSUE TITLE
Front-End :  Layouts - Create admin and user facing layouts

### ISSUE THREAD

**Issue by r00tmeister** [r00tmeister/group9_nuxt_fe#1]
### Description
Nuxt uses a Layout system with slots to inject pages into the layout structure. This reduces redundant code and make the updates more central.

As a developer I want to see the distinct navigation, layout and footers respectively

### Tasks
- [ ] Create a folder called layouts
- [ ] In the layout folder create two vue components one named index and one named admin
- [ ] Create Horizontal Navigation, Footer and Vertical Navigation components to be used in the layouts
- [ ] Create tags on the pages

### Acceptance Criteria
Clearly state the acceptance criteria to mark this issue as completed.
- [ ] Correct folder structure layout using the index and admin naming convetions
- [ ] Criteria 2

### Dependencies
List any dependencies or prerequisites, such as back-end APIs or third-party libraries.

### Additional Notes
Add any additional notes or references, such as design specs, browser compatibility, or related issues.
